name = "louvre"
account_id = "3bc1ba05af520b1b02c6222025200b06"
route = ""
workers_dev = true
compatibility_date = "2021-12-30"

[build]
command = "npm install && npm run build"

[[kv_namespaces]]
binding = "PHOTOS"
id = "90233aa3ce5a40de88573a97cb11faa2"
preview_id = "a6621ecc7c774e76b576d9f252338531"

[triggers]
crons = ["40 0 * * *"]
