name = "louvre"
type = "javascript"
zone_id = ""
account_id = "3bc1ba05af520b1b02c6222025200b06"
route = ""
workers_dev = true

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[[kv_namespaces]]
binding = "PHOTOS"
id = "90233aa3ce5a40de88573a97cb11faa2"
preview_id = "a6621ecc7c774e76b576d9f252338531"

[triggers]
crons = ["*/30 * * * *"]